# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './SensorTransformWidget/sensor_transform_dialog.ui',
# licensing of './SensorTransformWidget/sensor_transform_dialog.ui' applies.
#
# Created: Sun May 30 16:24:46 2021
#      by: pyside2-uic  running on PySide2 5.13.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(560, 304)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.baseLayout = QtWidgets.QHBoxLayout()
        self.baseLayout.setObjectName("baseLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.frameIdLabel = QtWidgets.QLabel(Dialog)
        self.frameIdLabel.setText("Frame ID")
        self.frameIdLabel.setObjectName("frameIdLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.frameIdLabel)
        self.frameIdLineEdit = QtWidgets.QLineEdit(Dialog)
        self.frameIdLineEdit.setObjectName("frameIdLineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.frameIdLineEdit)
        self.xLabel = QtWidgets.QLabel(Dialog)
        self.xLabel.setText("x [m]")
        self.xLabel.setObjectName("xLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.xLabel)
        self.xDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.xDoubleSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.xDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xDoubleSpinBox.setDecimals(3)
        self.xDoubleSpinBox.setMinimum(-100.0)
        self.xDoubleSpinBox.setMaximum(100.0)
        self.xDoubleSpinBox.setSingleStep(0.1)
        self.xDoubleSpinBox.setObjectName("xDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.xDoubleSpinBox)
        self.yLabel = QtWidgets.QLabel(Dialog)
        self.yLabel.setText("y [m]")
        self.yLabel.setObjectName("yLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.yLabel)
        self.yDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.yDoubleSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yDoubleSpinBox.setDecimals(3)
        self.yDoubleSpinBox.setMinimum(-100.0)
        self.yDoubleSpinBox.setMaximum(100.0)
        self.yDoubleSpinBox.setSingleStep(0.1)
        self.yDoubleSpinBox.setObjectName("yDoubleSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.yDoubleSpinBox)
        self.zLabel = QtWidgets.QLabel(Dialog)
        self.zLabel.setText("z [m]")
        self.zLabel.setObjectName("zLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.zLabel)
        self.zDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.zDoubleSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.zDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.zDoubleSpinBox.setDecimals(3)
        self.zDoubleSpinBox.setMinimum(-100.0)
        self.zDoubleSpinBox.setMaximum(100.0)
        self.zDoubleSpinBox.setSingleStep(0.1)
        self.zDoubleSpinBox.setObjectName("zDoubleSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.zDoubleSpinBox)
        self.rollLabel = QtWidgets.QLabel(Dialog)
        self.rollLabel.setText("roll [deg]")
        self.rollLabel.setObjectName("rollLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.rollLabel)
        self.rollDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.rollDoubleSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.rollDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.rollDoubleSpinBox.setDecimals(3)
        self.rollDoubleSpinBox.setMinimum(-180.0)
        self.rollDoubleSpinBox.setMaximum(180.0)
        self.rollDoubleSpinBox.setObjectName("rollDoubleSpinBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.rollDoubleSpinBox)
        self.pitchLabel = QtWidgets.QLabel(Dialog)
        self.pitchLabel.setText("pitch [deg]")
        self.pitchLabel.setObjectName("pitchLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.pitchLabel)
        self.pitchDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.pitchDoubleSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pitchDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.pitchDoubleSpinBox.setDecimals(3)
        self.pitchDoubleSpinBox.setMinimum(-180.0)
        self.pitchDoubleSpinBox.setMaximum(180.0)
        self.pitchDoubleSpinBox.setObjectName("pitchDoubleSpinBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.pitchDoubleSpinBox)
        self.yawLabel = QtWidgets.QLabel(Dialog)
        self.yawLabel.setText("yaw [deg]")
        self.yawLabel.setObjectName("yawLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.yawLabel)
        self.yawDoubleSpinBox = QtWidgets.QDoubleSpinBox(Dialog)
        self.yawDoubleSpinBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.yawDoubleSpinBox.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.yawDoubleSpinBox.setDecimals(3)
        self.yawDoubleSpinBox.setMinimum(-180.0)
        self.yawDoubleSpinBox.setMaximum(180.0)
        self.yawDoubleSpinBox.setObjectName("yawDoubleSpinBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.yawDoubleSpinBox)
        self.cameraLabel = QtWidgets.QLabel(Dialog)
        self.cameraLabel.setText("Camera")
        self.cameraLabel.setObjectName("cameraLabel")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.cameraLabel)
        self.cameraCheckBox = QtWidgets.QCheckBox(Dialog)
        self.cameraCheckBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cameraCheckBox.setText("")
        self.cameraCheckBox.setObjectName("cameraCheckBox")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.cameraCheckBox)
        self.baseLayout.addLayout(self.formLayout)
        self.viewLayout = QtWidgets.QVBoxLayout()
        self.viewLayout.setObjectName("viewLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.carlaRadioButton = QtWidgets.QRadioButton(Dialog)
        self.carlaRadioButton.setText("CARLA")
        self.carlaRadioButton.setChecked(True)
        self.carlaRadioButton.setObjectName("carlaRadioButton")
        self.buttonGroup = QtWidgets.QButtonGroup(Dialog)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.carlaRadioButton)
        self.horizontalLayout.addWidget(self.carlaRadioButton)
        self.hdf5RadioButton = QtWidgets.QRadioButton(Dialog)
        self.hdf5RadioButton.setText("HDF5")
        self.hdf5RadioButton.setObjectName("hdf5RadioButton")
        self.buttonGroup.addButton(self.hdf5RadioButton)
        self.horizontalLayout.addWidget(self.hdf5RadioButton)
        self.viewLayout.addLayout(self.horizontalLayout)
        self.baseLayout.addLayout(self.viewLayout)
        self.verticalLayout.addLayout(self.baseLayout)
        self.footerLayout = QtWidgets.QHBoxLayout()
        self.footerLayout.setObjectName("footerLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.footerLayout.addItem(spacerItem)
        self.okButton = QtWidgets.QPushButton(Dialog)
        self.okButton.setText("OK")
        self.okButton.setObjectName("okButton")
        self.footerLayout.addWidget(self.okButton)
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setText("Cancel")
        self.cancelButton.setObjectName("cancelButton")
        self.footerLayout.addWidget(self.cancelButton)
        self.verticalLayout.addLayout(self.footerLayout)

        # self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
